name: 'Reminder creator'
on:
  issue_comment:
    types: [created]
jobs:
  parse:
    if: ${{ contains(github.event.comment.body, '/remind') }}
    runs-on: ubuntu-latest
    
    steps:
      - name: check for reminder
        uses: agrc/create-reminder-action@v1.1.1